name: nano_city_services
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  #firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.4.9
  image_picker: ^1.1.1
  pin_code_fields: ^8.0.1
  firebase_app_check: ^0.3.2+9
  intl: ^0.19.0
  
  #google_maps_flutter: ^2.2.3
  #google_maps_flutter: ^2.1.1
  #geolocator: ^7.7.1
  #permission_handler: ^12.0.1  
  google_maps_flutter: ^2.6.0
  geolocator: ^9.0.2
  firebase_core: ^3.15.1
  location: ^5.0.0
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/mainlogo.png"
