// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn245_Zm2OxrNiAEHqXacKLEE58WVPQDQ',
    appId: '1:774800298554:web:9302bf55a94feada6ddb03',
    messagingSenderId: '774800298554',
    projectId: 'ncs-mca',
    authDomain: 'ncs-mca.firebaseapp.com',
    storageBucket: 'ncs-mca.firebasestorage.app',
    measurementId: 'G-Y04D20TKER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaT-mL0uoRZ3PFq7QRfTeTFO6y_UbYuP4',
    appId: '1:774800298554:android:b8b13a42776c57156ddb03',
    messagingSenderId: '774800298554',
    projectId: 'ncs-mca',
    storageBucket: 'ncs-mca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoreasS5a2CYImNbz6NTMa5XzeGT6bOu0',
    appId: '1:774800298554:ios:f0d488066f121b516ddb03',
    messagingSenderId: '774800298554',
    projectId: 'ncs-mca',
    storageBucket: 'ncs-mca.firebasestorage.app',
    iosBundleId: 'com.example.flutterHomeServiceProviderAppClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoreasS5a2CYImNbz6NTMa5XzeGT6bOu0',
    appId: '1:774800298554:ios:f0d488066f121b516ddb03',
    messagingSenderId: '774800298554',
    projectId: 'ncs-mca',
    storageBucket: 'ncs-mca.firebasestorage.app',
    iosBundleId: 'com.example.flutterHomeServiceProviderAppClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn245_Zm2OxrNiAEHqXacKLEE58WVPQDQ',
    appId: '1:774800298554:web:522894bed5fe95f26ddb03',
    messagingSenderId: '774800298554',
    projectId: 'ncs-mca',
    authDomain: 'ncs-mca.firebaseapp.com',
    storageBucket: 'ncs-mca.firebasestorage.app',
    measurementId: 'G-L1FN9ZQF6X',
  );
}
